-- Seed Settings (insert only if not exists to prevent overwriting user keys)
INSERT INTO settings (key_name, val_value) 
SELECT 'ELEVENLABS_API_KEY', '' FROM dual WHERE NOT EXISTS (SELECT 1 FROM settings WHERE key_name = 'ELEVENLABS_API_KEY');

INSERT INTO settings (key_name, val_value) 
SELECT 'ELEVENLABS_VOICE_ID', '' FROM dual WHERE NOT EXISTS (SELECT 1 FROM settings WHERE key_name = 'ELEVENLABS_VOICE_ID');

INSERT INTO settings (key_name, val_value) 
SELECT 'OPENROUTER_MODEL', 'anthropic/claude-opus-4.8' FROM dual WHERE NOT EXISTS (SELECT 1 FROM settings WHERE key_name = 'OPENROUTER_MODEL');


-- Seed Prompt History (upsert by ID)
MERGE INTO prompt_history (id, title, prompt) KEY(id) VALUES 
(1, 'Antigravity für Designer', 'Erstelle eine Präsentation über Antigravity für Designer. Sie soll locker und bildhaft sein. Kläre den Unterschied zwischen Chatbots und KI-Agenten. Zeige auf, dass Antigravity mehr als Text kann (z.B. Systemdiagnose, Ruckler beheben). Verwende das Bewerbungsprojekt als Praxisbeispiel (4 Teile: Unterlagen + Weblink, Masterprompt, Ergebnisse, Skripte/Tools).'),
(2, 'KI-Einsatz in Agenturen', 'Präsentation für Art Directors: Wie KI generative Bildgestaltung, UI Prototyping und repetitive Datei-Operationen automatisieren kann. Zeige konkrete Tool-Anbindungen und hebe hervor, dass kreative Kuration beim Menschen verbleibt.'),
(3, 'PC-Performance & Hardware für Designer', 'Erstelle einen Leitfaden für Kreative: Warum Photoshop, Illustrator und After Effects ruckeln. Diagnose-Schritte für CPU, RAM und VRAM, und wie man Caches automatisiert löschen kann.'),
(4, 'ElevenLabs API & Stimmenklon Guide', 'Erstelle eine Schritt-für-Schritt-Anleitung zur Nutzung von ElevenLabs. Zeige wie man einen Account anlegt, den API-Key ausliest, eine eigene Stimme per Instant Voice Cloning klont und die Voice-ID ausliest.');

-- Seed Example Project 1 (upsert by ID 1)
MERGE INTO projects (id, name, prompt, status, model_name, pptx_file_path, video_file_path, parent_id, version, version_group_id) KEY(id) VALUES 
(1, 'Antigravity - Einführung für Designer', 'Erstelle eine Präsentation über Antigravity für Designer. Sie soll locker und bildhaft sein. Kläre den Unterschied zwischen Chatbots und KI-Agenten. Zeige auf, dass Antigravity mehr als Text kann...', 'COMPLETED', 'anthropic/claude-opus-4.8', './data/projects/1/Antigravity_Vortrag.pptx', './data/projects/1/Antigravity_Vortrag_Video.mp4', NULL, 'v1', 1);

-- Seed Example Project 2 (upsert by ID 2)
MERGE INTO projects (id, name, prompt, status, model_name, pptx_file_path, video_file_path, parent_id, version, version_group_id) KEY(id) VALUES 
(2, 'ElevenLabs API & Stimmenklon Guide', 'Erstelle eine Schritt-für-Schritt-Anleitung zur Nutzung von ElevenLabs. Zeige wie man einen Account anlegt, den API-Key ausliest, eine eigene Stimme per Instant Voice Cloning klont und die Voice-ID ausliest.', 'COMPLETED', 'anthropic/claude-opus-4.8', './data/projects/2/presentation.pptx', './data/projects/2/presentation_video.mp4', NULL, 'v1', 2);

-- Seed slides for Example Project 1 (upsert by ID 1-10)
MERGE INTO slides (id, project_id, slide_number, title, bullets, notes, image_name, audio_file_path, video_file_path) KEY(id) VALUES 
(1, 1, 1, 'Antigravity', '["Dein neuer KI-Assistent.","Eine kreative, visuelle Einführung für Designer."]', 'Herzlich willkommen, liebe Kolleginnen und Kollegen aus dem Design! Heute möchte ich euch ''Antigravity'' vorstellen. Keine Sorge: Ihr müsst für diesen Vortrag nicht programmieren können und wir driften nicht in technische Details ab. Wir bleiben ganz an der Oberfläche. Ich zeige euch heute, was dieser neue KI-Assistent für euch tun kann und wie er euren Workflow vereinfacht – weit über das Schreiben von Standardtexten hinaus. Ich wünsche euch viel Spaß bei diesem Einblick!', 'mascot_hello.png', './data/projects/1/temp_audio/slide_1.mp3', './data/projects/1/temp_video/slide_1.mp4'),
(2, 1, 2, 'Was ist Antigravity?', '["Ein ''Agentic AI''-Assistent (ein KI-Agent)","Läuft direkt in deiner lokalen Arbeitsumgebung","Kann selbstständig Dateien lesen, erstellen & bearbeiten","Führt komplexe Workflows vollautomatisch aus","Arbeitet mit echten Tools, Skripten und Websuchen"]', 'Was genau ist Antigravity eigentlich? Ihr kennt wahrscheinlich alle ChatGPT oder Claude im Webbrowser. Das sind reine Chatbots: Man stellt eine Frage, bekommt eine Textantwort und muss das Ergebnis kopieren. Antigravity hingegen ist ein sogenannter ''KI-Agent''. Das bedeutet vereinfacht gesagt: Er hat Hände und Augen auf eurem Computer. Er arbeitet direkt in euren Projektordnern, kann eure lokalen Dateien lesen, neue Entwürfe speichern, im Web recherchieren und sogar Programme oder Skripte ausführen, um seine Aufgaben für euch zu erledigen. Er ist wie ein fleißiger digitaler Junior-Assistent.', 'mascot_think.png', './data/projects/1/temp_audio/slide_2.mp3', './data/projects/1/temp_video/slide_2.mp4'),
(3, 1, 3, 'Mehr als nur Anschreiben!', '["Hilft bei lästigen Routineaufgaben im Betriebssystem","Beantwortet Alltagsfragen zu deiner Hardware","Analysiert verständlich, warum dein PC langsam ist","Findet die Ursache, wenn Programme oder die Maus ruckeln","Prüft, ob Festplatte und Arbeitsspeicher in Ordnung sind"]', 'Die meisten Leute denken bei KI an Texte oder Übersetzungen. Aber Antigravity kann noch viel mehr in eurem Alltag tun. Kennt ihr das, wenn Photoshop oder Illustrator plötzlich laggen, der Mauszeiger zackig ruckelt oder die Festplatte fast voll ist? Typische Designer-Probleme, wenn man mit riesigen Texturen und Grafiken hantiert. Anstatt stundenlang in technischen Foren zu suchen, könnt ihr Antigravity einfach fragen: ''Warum ruckelt mein Rechner gerade?'' oder ''Habe ich noch genug Speicher?''. Er schaut direkt im System nach und liefert die Antwort.', 'slow_pc.png', './data/projects/1/temp_audio/slide_3.mp3', './data/projects/1/temp_video/slide_3.mp4'),
(4, 1, 4, 'Dein persönlicher PC-Doktor', '["Systemdiagnose ganz ohne technisches Kauderwelsch","Echtzeit-Check von CPU-Last, RAM und Speicherplatz","Identifiziert Programme, die deine Grafikkarte blockieren","Gibt dir konkrete, leicht verständliche Optimierungs-Tipps","Hilft aktiv beim Aufräumen (z. B. Temp-Dateien löschen)"]', 'Antigravity agiert hier wie euer persönlicher PC-Doktor. Er schaut quasi unter die Haube eures Rechners. Er analysiert die CPU, den RAM und die Belegung der Festplatten und übersetzt das in eine für uns Designer verständliche Sprache. Er sagt euch zum Beispiel: ''Hey, das Rendering-Programm im Hintergrund frisst 90% deines Speichers.'' Auf Wunsch kann er auch gleich beim Aufräumen helfen und temporären Datenmüll löschen, damit eure Kreativ-Software wieder flüssig läuft.', 'pc_doctor.png', './data/projects/1/temp_audio/slide_4.mp3', './data/projects/1/temp_video/slide_4.mp4'),
(5, 1, 5, 'Praxisbeispiel: Die Bewerbungs-Fabrik', '["Vorstellung des Projekts ''Bewerbungen2''","Problem: Manuelle Bewerbungen kosten enorm viel Zeit","Anschreiben müssen individuell auf jede Agentur passen","Lebensläufe müssen die Sprache des Zielunternehmens sprechen","Fehleranfälligkeit bei manuellem Copy-Paste"]', 'Um zu verdeutlichen, wie mächtig Antigravity ist, schauen wir uns ein konkretes Praxisbeispiel an: das Projekt ''Bewerbungen2''. Stellt euch vor, ihr wollt euch bei 10 verschiedenen Design-Agenturen bewerben. Jede Agentur hat einen anderen Fokus: Die eine macht Corporate Identity, die nächste UI/UX-Design, eine andere Packaging. Jedes Anschreiben und jeder Lebenslauf müsste manuell an das Portfolio der jeweiligen Agentur angepasst werden. Das dauert Tage und ist unglaublich eintönig. Antigravity verwandelt dieses Chaos in eine vollautomatische Pipeline.', 'paper_chaos.png', './data/projects/1/temp_audio/slide_5.mp3', './data/projects/1/temp_video/slide_5.mp4'),
(6, 1, 6, 'Schritt 1: Die KI lernt dich kennen', '["Basis-Daten: Lebenslauf & Zeugnisse im Ordner ''bewerbungsunterlagen''","Zusätzliche Quelle: Deine persönliche Website (z. B. www.tnickel-ki.de)","KI analysiert deine Design-Philosophie und Stärken","Identifiziert selbstständig passende Unternehmen im Web","Erstellt eine Vorschlagsliste und wartet auf dein Okay"]', 'Im ersten Schritt muss die KI natürlich erst mal verstehen, wer ihr seid. Im Ordner ''bewerbungsunterlagen'' liegen eure Standard-Dokumente wie eure Basis-Lebenslauf, Zertifikate und Zeugnisse. Zusätzlich geben wir der KI einen Weblink zu eurer Online-Präsenz – hier im Beispiel www.tnickel-ki.de. Antigravity liest die Website und eure Dokumente und baut ein tiefes Verständnis für eure Fähigkeiten, euren Design-Stil und eure Schwerpunkte auf. Anschließend sucht er im Web nach 4 bis 5 hochkarätigen Agenturen, die perfekt zu eurem Profil passen, und fragt euch um Erlaubnis, ob er für diese die Unterlagen vorbereiten soll.', 'research_you.png', './data/projects/1/temp_audio/slide_6.mp3', './data/projects/1/temp_video/slide_6.mp4'),
(7, 1, 7, 'Schritt 2: Der Master-Prompt (Der Dirigent)', '["Gesteuert über eine zentrale Textdatei: doc/masterprompt.txt","Definiert den exakten ''Fahrplan'' für die Pipeline","Zwingt die KI zur Live-Websuche vor der Dokumenterstellung","Sucht nach aktuellen News, Projekten und Tech-Stacks der Firmen","Nutzt diese Recherche als ''kreativen Aufhänger'' im Anschreiben"]', 'Der gesamte Ablauf wird durch den ''Master-Prompt'' gesteuert, der im Ordner ''doc'' liegt. Für uns Designer ist dieser Prompt wie ein Creative Director oder Dirigent. Es ist eine einfache Textdatei, die der KI sagt, wie sie vorgehen soll. Ein Kernbefehl darin ist der Deep-Research-Zwang: Bevor die KI ein Wort schreibt, muss sie das Zielunternehmen im Web suchen. Welche Kampagnen hat die Agentur in den letzten Monaten gelauncht? Welche Kunden betreuen sie? Diese echten Fakten baut Antigravity direkt als Aufhänger in eure Anschreiben ein, um echtes interesse zu signalisieren.', 'conductor.png', './data/projects/1/temp_audio/slide_7.mp3', './data/projects/1/temp_video/slide_7.mp4'),
(8, 1, 8, 'Schritt 3: Die Skripte (Die Werkzeuge)', '["Automatisierung durch Code im Ordner skripte","KI schreibt und nutzt kleine Helfer-Skripte (Python/PowerShell)","Konvertiert Markdown-Entwürfe automatisch in saubere PDFs","Kombiniert Anschreiben, Lebenslauf und Zeugnisse in Mappen","Räumt den Arbeitsbereich auf und löscht temporäre Dateien"]', 'Jetzt kommt das Handwerk. Um aus den generierten Texten fertige, versandbereite Mappen zu machen, nutzt Antigravity Skripte im Ordner ''skripte''. Für uns Designer ist das vergleichbar mit Photoshop-Aktionen oder Illustrator-Makros. Der Agent schreibt diese Skripte selbstständig oder führt sie aus. Sie wandeln die Textdokumente in PDF-Dateien um, bündeln das Anschreiben mit dem Lebenslauf und kopieren eure Zeugnisse dazu. Am Ende löscht die KI alle temporären Arbeitsdateien, damit kein Chaos auf eurer Festplatte entsteht.', 'toolbox.png', './data/projects/1/temp_audio/slide_8.mp3', './data/projects/1/temp_video/slide_8.mp4'),
(9, 1, 9, 'Schritt 4: Die fertigen Ergebnisse', '["Hauptordner Initiativbewerbungen_Aktuell wird erstellt","Saubere Unterordner für jedes einzelne Zielunternehmen","Individuell getextete, professionell formatierte Anschreiben & CVs","Alle Dokumente direkt als druck- und versandfertige PDFs","Walkthrough-Dokument verlinkt alle Ergebnisse direkt"]', 'Das Ergebnis ist einfach fantastisch. Nach nur wenigen Minuten findet ihr im Ordner ''Initiativbewerbungen_Aktuell'' für jedes Zielunternehmen einen perfekt sortierten Ordner. Darin liegen das fertige, personalisierte Anschreiben und der angepasste Lebenslauf als PDF, bereit zum Abschicken. Zusätzlich erstellt Antigravity eine kleine Übersichtsdatei, in der alle PDFs direkt verlinkt sind. Ihr könnt sie mit einem Klick öffnen, prüfen und abschicken. Die Arbeit von mehreren Tagen wurde in wenigen Minuten erledigt.', 'results_trophy.png', './data/projects/1/temp_audio/slide_9.mp3', './data/projects/1/temp_video/slide_9.mp4'),
(10, 1, 10, 'Kreativität entfesseln mit Antigravity', '["Die KI übernimmt die repetitive, zeitraubende Fleißarbeit","Der Mensch bleibt der Kurator, Designer und Entscheider","Mehr Zeit für das Wesentliche: Echte Designarbeit & Konzepte","Nahtlose Integration in deinen täglichen Workflow","Dein unsichtbarer, helfender Assistent im System"]', 'Zusammenfassend: Was bedeutet das für uns als Designer? Antigravity nimmt uns nicht die kreative Arbeit oder die gestalterische Vision weg. Es nimmt uns die administrative Fleißarbeit ab – das Suchen von Firmeninfos, das Anpassen von Texten, das Formatieren und Konvertieren von Dateien oder das Lösen von PC-Rucklern. Wir bleiben die Entscheider, die die finalen Ergebnisse freigeben. So haben wir den Kopf frei für das, was wir wirklich lieben: exzellentes Design und innovative Ideen. Vielen Dank für eure Aufmerksamkeit!', 'speed_boost.png', './data/projects/1/temp_audio/slide_10.mp3', './data/projects/1/temp_video/slide_10.mp4');

-- Seed slides for Example Project 2 (upsert by ID 11-15)
MERGE INTO slides (id, project_id, slide_number, title, bullets, notes, image_name, audio_file_path, video_file_path) KEY(id) VALUES 
(11, 2, 1, 'ElevenLabs API & Stimmenklon Guide', '["Eine Schritt-für-Schritt-Anleitung","für die Vertonung deines Vortrags."]', 'Herzlich willkommen! In diesem kurzen Leitfaden zeige ich dir Schritt für Schritt, wie du deinen ElevenLabs-Account einrichtest, deine eigene Stimme klonst und die notwendigen Schlüssel für unseren Vortragsgenerator erhältst. Keine Sorge – das Ganze dauert nur wenige Minuten und ist extrem unkompliziert. Lass uns direkt mit dem ersten Schritt starten!', 'mascot_hello.png', './data/projects/2/audio/slide_1.mp3', NULL),
(12, 2, 2, 'Schritt 1: Account erstellen', '["Besuche die Webseite elevenlabs.io", "Erstelle einen kostenlosen Account", "Anmeldung via E-Mail, Google oder GitHub", "Automatisch freies monatliches Zeichenkontingent"]', 'Als Erstes gehen wir auf die Website elevenlabs.io. Dort kannst du dich ganz einfach registrieren – entweder klassisch mit deiner E-Mail-Adresse oder direkt über deinen bestehenden Google- oder GitHub-Account. Nach der Anmeldung hast du sofort Zugriff auf das Dashboard und ein monatliches Freikontingent an Zeichen für die Sprachsynthese.', 'mascot_think.png', './data/projects/2/audio/slide_2.mp3', NULL),
(13, 2, 3, 'Schritt 2: API-Schlüssel kopieren', '["Klicke unten links auf dein Profil-Symbol", "Wähle den Menüpunkt ''Profile + API-Keys''", "Klicke auf das Auge-Symbol zum Einblenden", "Kopiere den API-Schlüssel in unseren Generator"]', 'Um unseren Vortragsgenerator mit ElevenLabs zu verbinden, benötigen wir einen API-Schlüssel. Klicke dazu unten links in deinem ElevenLabs-Dashboard auf dein Profilbild oder deinen Benutzernamen und wähle den Menüpunkt ''Profile + API-Keys''. Dort siehst du deinen API-Schlüssel. Klicke auf das kleine Auge-Symbol, um ihn anzuzeigen, und kopiere ihn in die Einstellungen unseres Generators.', 'toolbox.png', './data/projects/2/audio/slide_3.mp3', NULL),
(14, 2, 4, 'Schritt 3: Eigene Stimme klonen', '["Gehe links im Menü auf ''Voices''", "Klicke auf ''Add voice'' und wähle ''Instant Voice Cloning''", "Lade eine 1-2 minütige Sprachaufnahme von dir hoch", "Achte auf eine ruhige Umgebung ohne Hintergrundgeräusche"]', 'Jetzt klonen wir deine Stimme! Klicke im Menü links auf ''Voices'' und dann auf ''Add voice''. Wähle dort ''Instant Voice Cloning''. Lade nun eine kurze Audioaufnahme von dir hoch. Am besten nimmst du dich mit dem Handy oder Mikrofon für etwa 1 bis 2 Minuten in einer absolut ruhigen Umgebung auf, während du einen deutschen Text vorliest. Je sauberer die Aufnahme ist, desto originalgetreuer klingt am Ende deine KI-Stimme.', 'pc_doctor.png', './data/projects/2/audio/slide_4.mp3', NULL),
(15, 2, 5, 'Schritt 4: Voice-ID kopieren', '["Deine Klonstimme erscheint in der Voices-Bibliothek", "Klicke auf das kleine ID-Symbol unter dem Namen", "Kopiere die eindeutige Voice-ID Zeichenkette", "Füge sie in die Einstellungen des Generators ein"]', 'Sobald die Stimme erstellt ist, erscheint sie in deiner Stimmen-Bibliothek. Direkt unter dem Namen deiner Klonstimme siehst du ein kleines ID-Symbol (oder einen Textlink ''ID anzeigen''). Klicke darauf und kopiere die eindeutige ID-Zeichenfolge. Diese ID fügst du in den Einstellungen unseres Vortragsgenerators ein. Nun ist das System bereit und du kannst deine Vorträge vollautomatisch mit deiner eigenen Stimme vertonen lassen!', 'results_trophy.png', './data/projects/2/audio/slide_5.mp3', NULL);

-- Seed Example Project 3 (upsert by ID 3)
MERGE INTO projects (id, name, prompt, status, model_name, pptx_file_path, video_file_path, parent_id, version, version_group_id) KEY(id) VALUES 
(3, 'Vortragsgenerator - Der Überblick', 'Erstelle eine Präsentation über den Vortragsgenerator. Lobe das Produkt aus Sicht eines Nicht-Technikers. Zeige alle Features, die autonome Recherche, die Prompt-Eingabe, custom Bilder und die Stimmsynthese mit ElevenLabs.', 'COMPLETED', 'Manual-JSON-Import', './data/projects/3/presentation.pptx', './data/projects/3/presentation_video.mp4', NULL, 'v1', 3);

-- Seed slides for Example Project 3 (upsert by ID 16-35)
MERGE INTO slides (id, project_id, slide_number, title, bullets, notes, image_name, audio_file_path, video_file_path) KEY(id) VALUES 
(16, 3, 1, 'Der Vortragsgenerator', '["Präsentationen neu gedacht","KI-gestützte Recherche, Folienerstellung & Vertonung","In wenigen Minuten zum fertigen Vortragsvideo","Dein persönlicher Vortrags-Assistent"]', 'Herzlich willkommen! Heute möchte ich Ihnen ein Werkzeug vorstellen, das die Art und Weise, wie wir Präsentationen und Videos erstellen, grundlegend verändert: den Vortragsgenerator. Stellen Sie sich vor, Sie haben eine Idee für ein Thema, und in nur wenigen Minuten haben Sie nicht nur fertige Folien, sondern ein komplett vertontes Video mit Ihrer eigenen Stimme. Ganz ohne technisches Vorwissen. Lassen Sie uns gemeinsam entdecken, wie einfach das funktioniert!', 'mascot_hello.png', './data/projects/3/audio/slide_1.mp3', NULL),
(17, 3, 2, 'Das Problem klassischer Vorträge', '["Stundenlange Recherche in Suchmaschinen","Mühsame Gestaltung von PowerPoint-Folien","Schreiben von Redetexten kostet Zeit und Nerven","Manuelle Video- und Audio-Bearbeitung ist kompliziert"]', 'Jeder von uns kennt es: Man muss einen Vortrag halten oder ein Erklärvideo erstellen. Erst recherchiert man stundenlang, dann quält man sich mit dem Design der Folien, schreibt ewig am Redetext und am Ende muss man das Ganze auch noch einsprechen und mit einem Videoschnittprogramm schneiden. Das kostet Tage und oft auch den letzten Nerv. Der Vortragsgenerator löst all diese Probleme auf einmal.', 'paper_chaos.png', './data/projects/3/audio/slide_2.mp3', NULL),
(18, 3, 3, 'Die Vision – Alles aus einer Hand', '["Ein einziger Text-Prompt startet den Prozess","Autonome Recherche im Hintergrund","Automatischer Folien-Entwurf und Layout","Natürliche Vertonung mit geklonter Stimme"]', 'Die Vision hinter dem Vortragsgenerator ist bestechend einfach: Sie geben lediglich das Thema oder eine Idee in Form eines kurzen Textes ein. Den Rest erledigt das System für Sie. Es recherchiert, strukturiert die Inhalte, designt die Folien, formuliert den gesprochenen Text aus und vertont das fertige Video. Am Ende erhalten Sie eine PowerPoint-Datei und ein fertiges Video.', 'speed_boost.png', './data/projects/3/audio/slide_3.mp3', NULL),
(19, 3, 4, 'Das Herzstück – Der Prompt-Eingabe', '["Einfache, menschliche Sprache genügt","Keine Programmierkenntnisse oder Fachbegriffe nötig","Definiere Zielgruppe, Tonfall und Schwerpunkte","Beispiel: ''Erkläre Quantencomputer für Schüler''"]', 'Alles beginnt mit der Prompt-Eingabe. Ein Prompt ist nichts anderes als eine Beschreibung in normaler deutscher Sprache. Sie müssen keine komplizierten Befehle kennen. Schreiben Sie einfach auf, worüber Sie sprechen möchten, wen Sie ansprechen wollen und welchen Stil Sie bevorzugen. Das System versteht Sie und passt den gesamten Vortrag darauf an.', 'mascot_think.png', './data/projects/3/audio/slide_4.mp3', NULL),
(20, 3, 5, 'Autonome Web-Recherche', '["Die KI sucht im Internet nach aktuellen Fakten","Verwendung von verlässlichen Quellen","Strukturierung der Informationen im Hintergrund","Keine veralteten Daten oder ''Halluzinationen''"]', 'Nachdem Sie den Prompt abgeschickt haben, geht die KI für Sie auf Entdeckungsreise im Web. Sie sucht nach aktuellen Zahlen, Daten und Fakten zu Ihrem Thema. So wird sichergestellt, dass Ihr Vortrag auf echten und aktuellen Informationen basiert, ohne dass Sie selbst stundenlang Suchmaschinen durchforsten müssen.', 'research_you.png', './data/projects/3/audio/slide_5.mp3', NULL),
(21, 3, 6, 'Automatische Folienerstellung', '["Generierung einer sauberen Präsentationsstruktur","Automatische Aufteilung in sinnvolle Abschnitte","Verteilung von Kernaussagen auf die Folien","Fokus auf Lesbarkeit und Übersichtlichkeit"]', 'Basierend auf den recherchierten Daten erstellt das System eine logische Gliederung. Es teilt das Thema in mundgerechte Folien auf, formuliert prägnante Überschriften und Stichpunkte. Jede Folie konzentriert sich auf ein bis zwei Kernbotschaften, damit Ihr Publikum dem Vortrag mühelos folgen kann.', 'toolbox.png', './data/projects/3/audio/slide_6.mp3', NULL),
(22, 3, 7, 'Der Redetext (Speaker Notes)', '["Jede Folie erhält einen maßgeschneiderten Redetext","Flüssig geschriebener Sprechstil (kein Vorlesen der Folien)","Perfekt abgestimmt auf die visuellen Inhalte","Individuell anpassbar vor der Vertonung"]', 'Gleichzeitig mit den Folien schreibt die KI den genauen Sprechtext für Sie. Dieser Text steht später in den ''Notizen'' der Präsentation. Der Stil ist extra so formuliert, dass er gesprochen natürlich und lebendig klingt – er ergänzt die Stichpunkte auf der Folie, anstatt sie einfach nur platt vorzulesen.', 'conductor.png', './data/projects/3/audio/slide_7.mp3', NULL),
(23, 3, 8, 'Premium Bilder für jede Folie', '["Automatische Auswahl passender Grafiken","Harmonische Farbpaletten und Premium-Optik","Vermeidung von langweiligen Standard-Stockfotos","Sympathische Mascot-Illustrationen lockern auf"]', 'Eine Präsentation lebt von Bildern. Der Vortragsgenerator wählt automatisch aus einer Bibliothek von liebevoll gestalteten Maskottchen-Illustrationen das Bild aus, das inhaltlich am besten zu Ihrer Folie passt. Das sorgt für ein einheitliches, modernes Design und lockert das Thema sympathisch auf.', 'mascot_hello.png', './data/projects/3/audio/slide_8.mp3', NULL),
(24, 3, 9, 'Eigene Bilder & Screenshots hinzufügen', '["Lade eigene Grafiken oder Fotos hoch","Füge eine kurze Erklärung für die KI hinzu","Die KI bindet die Bilder intelligent in die Folien ein","Ideal für Produkt-Demos, Logos oder Beispieldateien"]', 'Sie möchten Ihre eigenen Produktbilder, Screenshots oder Teamfotos zeigen? Kein Problem! Sie können eigene Bilddateien hochladen und der KI kurz beschreiben, was darauf zu sehen ist. Die KI versteht diese Beschreibungen und platziert Ihre Bilder genau auf den passenden Folien im Vortrag.', 'toolbox.png', './data/projects/3/audio/slide_9.mp3', NULL),
(25, 3, 10, 'ElevenLabs – Die Stimme des Vortrags', '["Einbindung der weltweit führenden Stimmsynthese","Kristallklare Tonqualität ohne Rauschen","Natürliche Betonung, Pausen und Atmer","Unterstützung für über 29 Sprachen"]', 'Für den Ton arbeitet der Vortragsgenerator mit ElevenLabs zusammen, der besten KI-Stimmen-Technologie auf dem Markt. Ihre Präsentation wird nicht von einem Roboter vorgelesen, sondern klingt absolut professionell, lebendig und flüssig – mit den richtigen Betonungen und natürlichem Sprechtempo.', 'pc_doctor.png', './data/projects/3/audio/slide_10.mp3', NULL),
(26, 3, 11, 'Instant Voice Cloning – Deine eigene Stimme', '["Klonen der eigenen Stimme in unter 2 Minuten","Erfordert nur eine kurze, saubere Sprachaufnahme","Maximale persönliche Note für deine Videos","Niemand bemerkt den Unterschied zur echten Aufnahme"]', 'Das absolute Highlight: Sie können Ihre eigene Stimme klonen! Laden Sie einfach eine kurze Sprachaufnahme von sich hoch. ElevenLabs erstellt daraus ein digitales Stimmprofil. Der Vortragsgenerator liest die Sprechtexte dann mit Ihrer geklonten Stimme vor. So klingt das Video am Ende exakt so, als hätten Sie es selbst eingesprochen.', 'results_trophy.png', './data/projects/3/audio/slide_11.mp3', NULL),
(27, 3, 12, 'Der Video-Generator im Einsatz', '["Automatische Synchronisation von Bild und Ton","Erstellung von Einzelvideos pro Folie","Zusammenfügen zum finalen Gesamtvideo","Kein manueller Videoschnitt notwendig"]', 'Im Hintergrund läuft ein vollautomatischer Videoschnitt. Der Generator nimmt das Bild jeder Folie, legt die passende Audiospur darunter, ermittelt die exakte Länge der gesprochenen Worte und erstellt daraus einen Video-Clip. Am Ende werden diese Clips nahtlos zu einem flüssigen Gesamtvideo im MP4-Format zusammengefügt.', 'toolbox.png', './data/projects/3/audio/slide_12.mp3', NULL),
(28, 3, 13, 'PowerPoint (PPTX) Export', '["Vollwertiger Download der PowerPoint-Datei","Folien und Texte bleiben 100% editierbar","Freie Wahl der Schriftarten und Layouts in Office","Perfekt für manuelle Nachbearbeitungen"]', 'Sie erhalten nicht nur ein fertiges Video, sondern können auch die PowerPoint-Datei selbst herunterladen. Alle Folien, Überschriften, Stichpunkte und Sprechtexte in den Notizen sind editierbar. So können Sie vor einem Live-Vortrag noch schnell Anpassungen vornehmen oder Ihr Firmenlogo einbauen.', 'results_trophy.png', './data/projects/3/audio/slide_13.mp3', NULL),
(29, 3, 14, 'Versionierung und Klonen', '["Erstelle mehrere Versionen eines Vortrags","Probiere verschiedene Prompts oder Modelle aus","Klonen per Knopfdruck sichert den aktuellen Stand","Vergleiche Entwürfe ohne Datenverlust"]', 'Der Vortragsgenerator verfügt über eine eingebaute Versionsverwaltung. Sie können einen bestehenden Vortrag einfach duplizieren, den Prompt anpassen und eine neue Version generieren lassen. So können Sie verschiedene Ideen oder Zielgruppen-Formulierungen spielerisch vergleichen, ohne Ihren alten Stand zu verlieren.', 'conductor.png', './data/projects/3/audio/slide_14.mp3', NULL),
(30, 3, 15, 'Die H2-Datenbank im Hintergrund', '["Lokale, sichere Speicherung aller Daten","Keine Cloud-Registrierung für deine Projekthistorie","Historie speichert genutzte Prompts","Schnelles Laden durch lokale Datenbank-Technologie"]', 'Datenschutz und Geschwindigkeit werden großgeschrieben. Alle Ihre Projekte, Texte und Einstellungen werden in einer lokalen Datenbank direkt auf Ihrem Computer gespeichert. Ihre Prompts werden in einer Historie gesichert, so dass Sie einmal geschriebene Prompts jederzeit wiederverwenden können.', 'pc_doctor.png', './data/projects/3/audio/slide_15.mp3', NULL),
(31, 3, 16, 'Flexibler Import vorhandener Folien', '["Lade eine vorhandene PowerPoint-Datei hoch","Die KI analysiert und importiert die Folien","Füge nachträglich Sprechtexte und Vertonungen hinzu","Mache aus alten Folien moderne Videos"]', 'Haben Sie bereits fertige Folien, die Sie vertonen möchten? Auch das ist möglich! Laden Sie einfach Ihre bestehende PowerPoint-Datei hoch. Das System importiert die Folienstruktur, und Sie können im Editor Sprechtexte ergänzen und das Video direkt generieren lassen.', 'toolbox.png', './data/projects/3/audio/slide_16.mp3', NULL),
(32, 3, 17, 'Warum das Tool begeistert (Der Nutzen)', '["Zeitersparnis von bis zu 90%","Keine Angst mehr vor dem leeren Blatt","Professioneller Auftritt in Bild und Ton","Mehr Fokus auf die Botschaft statt auf die Technik"]', 'Der Nutzen liegt auf der Hand: Sie sparen bis zu 90% der Zeit, die Sie normalerweise für die Erstellung eines Vortrags benötigen würden. Die KI nimmt Ihnen die Schreibblockade und die Fleißarbeit ab. Sie können sich voll und ganz auf den Inhalt und die Botschaft konzentrieren.', 'speed_boost.png', './data/projects/3/audio/slide_17.mp3', NULL),
(33, 3, 18, 'Anwendungsbereiche des Generators', '["Schulungsvideos und Tutorials für Mitarbeiter","Einfache Produktpräsentationen für Kunden","Referate und Vorträge für Schule und Studium","Social Media Beiträge und Kurzerklärungen"]', 'Die Einsatzmöglichkeiten sind grenzenlos. Ob Sie neue Mitarbeiter einarbeiten möchten, ein Produkt für Kunden erklären, ein Schulreferat vorbereiten oder kurze Erklärvideos für soziale Medien erstellen wollen – der Vortragsgenerator ist Ihr universeller Befehlshaber.', 'mascot_hello.png', './data/projects/3/audio/slide_18.mp3', NULL),
(34, 3, 19, 'So startest du durch (Die 3 Schritte)', '["Schritt 1: API-Keys eintragen (OpenRouter & ElevenLabs)","Schritt 2: Prompt eingeben oder Folien hochladen","Schritt 3: Generieren drücken und Video herunterladen"]', 'Wie legen Sie los? In nur drei einfachen Schritten: Tragen Sie Ihre API-Keys in den Einstellungen ein. Geben Sie Ihren Prompt ein. Klicken Sie auf ''Generieren''. Nach wenigen Minuten halten Sie Ihr fertiges Video und Ihre PowerPoint-Präsentation in den Händen. Es ist wirklich so einfach!', 'conductor.png', './data/projects/3/audio/slide_19.mp3', NULL),
(35, 3, 20, 'Zusammenfassung & Ausblick', '["Der Vortragsgenerator macht Videoerstellung für jeden möglich","Professionelle Ergebnisse ohne teures Equipment","Deine Stimme, deine Folien, vollautomatisch","Probiere es jetzt aus und lass dich begeistern!"]', 'Zusammenfassend lässt sich sagen: Der Vortragsgenerator demokratisiert die Videoerstellung. Sie benötigen kein teures Aufnahme-Equipment, keine Sprecherausbildung und kein Schnittprogramm. Probieren Sie es selbst aus, erstellen Sie Ihren ersten Vortrag und begeistern Sie Ihr Publikum! Vielen Dank für Ihre Aufmerksamkeit.', 'results_trophy.png', './data/projects/3/audio/slide_20.mp3', NULL);


-- Restart auto-increment sequences dynamically based on the max ID in the tables to prevent primary key collisions on server restarts
ALTER TABLE projects ALTER COLUMN id RESTART WITH (SELECT COALESCE(MAX(id), 0) + 1 FROM projects);
ALTER TABLE slides ALTER COLUMN id RESTART WITH (SELECT COALESCE(MAX(id), 0) + 1 FROM slides);
ALTER TABLE prompt_history ALTER COLUMN id RESTART WITH (SELECT COALESCE(MAX(id), 0) + 1 FROM prompt_history);
ALTER TABLE image_sets ALTER COLUMN id RESTART WITH (SELECT COALESCE(MAX(id), 0) + 1 FROM image_sets);

