-- Seed Settings (upsert by unique key_name)
MERGE INTO settings (key_name, val_value) KEY(key_name) VALUES 
('ELEVENLABS_API_KEY', ''),
('ELEVENLABS_VOICE_ID', ''),
('OPENROUTER_MODEL', 'anthropic/claude-opus-4.8');

-- Seed Prompt History (upsert by ID)
MERGE INTO prompt_history (id, title, prompt) KEY(id) VALUES 
(1, 'Antigravity für Designer', 'Erstelle eine Präsentation über Antigravity für Designer. Sie soll locker und bildhaft sein. Kläre den Unterschied zwischen Chatbots und KI-Agenten. Zeige auf, dass Antigravity mehr als Text kann (z.B. Systemdiagnose, Ruckler beheben). Verwende das Bewerbungsprojekt als Praxisbeispiel (4 Teile: Unterlagen + Weblink, Masterprompt, Ergebnisse, Skripte/Tools).'),
(2, 'KI-Einsatz in Agenturen', 'Präsentation für Art Directors: Wie KI generative Bildgestaltung, UI Prototyping und repetitive Datei-Operationen automatisieren kann. Zeige konkrete Tool-Anbindungen und hebe hervor, dass kreative Kuration beim Menschen verbleibt.'),
(3, 'PC-Performance & Hardware für Designer', 'Erstelle einen Leitfaden für Kreative: Warum Photoshop, Illustrator und After Effects ruckeln. Diagnose-Schritte für CPU, RAM und VRAM, und wie man Caches automatisiert löschen kann.'),
(4, 'ElevenLabs API & Stimmenklon Guide', 'Erstelle eine Schritt-für-Schritt-Anleitung zur Nutzung von ElevenLabs. Zeige wie man einen Account anlegt, den API-Key ausliest, eine eigene Stimme per Instant Voice Cloning klont und die Voice-ID ausliest.');

-- Seed Example Project 1 (upsert by ID 1)
MERGE INTO projects (id, name, prompt, status, model_name, pptx_file_path, video_file_path, parent_id, version, version_group_id) KEY(id) VALUES 
(1, 'Antigravity - Einführung für Designer', 'Erstelle eine Präsentation über Antigravity für Designer. Sie soll locker und bildhaft sein. Kläre den Unterschied zwischen Chatbots und KI-Agenten. Zeige auf, dass Antigravity mehr als Text kann...', 'COMPLETED', 'anthropic/claude-opus-4.8', './data/projects/1/Antigravity_Vortrag.pptx', './data/projects/1/Antigravity_Vortrag_Video.mp4', NULL, 'v1', 1);

-- Seed Example Project 2 (upsert by ID 2)
MERGE INTO projects (id, name, prompt, status, model_name, pptx_file_path, video_file_path, parent_id, version, version_group_id) KEY(id) VALUES 
(2, 'ElevenLabs API & Stimmenklon Guide', 'Erstelle eine Schritt-für-Schritt-Anleitung zur Nutzung von ElevenLabs. Zeige wie man einen Account anlegt, den API-Key ausliest, eine eigene Stimme per Instant Voice Cloning klont und die Voice-ID ausliest.', 'COMPLETED', 'anthropic/claude-opus-4.8', './data/projects/2/presentation.pptx', './data/projects/2/presentation_video.mp4', NULL, 'v1', 2);

-- Seed slides for Example Project 1 (upsert by ID 1-10)
MERGE INTO slides (id, project_id, slide_number, title, bullets, notes, image_name, audio_file_path, video_file_path) KEY(id) VALUES 
(1, 1, 1, 'Antigravity', '["Dein neuer KI-Assistent.","Eine kreative, visuelle Einführung für Designer."]', 'Herzlich willkommen, liebe Kolleginnen und Kollegen aus dem Design! Heute möchte ich euch ''Antigravity'' vorstellen. Keine Sorge: Ihr müsst für diesen Vortrag nicht programmieren können und wir driften nicht in technische Details ab. Wir bleiben ganz an der Oberfläche. Ich zeige euch heute, was dieser neue KI-Assistent für euch tun kann und wie er euren Workflow vereinfacht – weit über das Schreiben von Standardtexten hinaus. Ich wünsche euch viel Spaß bei diesem Einblick!', 'mascot_hello.png', './data/projects/1/temp_audio/slide_1.mp3', './data/projects/1/temp_video/slide_1.mp4'),
(2, 1, 2, 'Was ist Antigravity?', '["Ein ''Agentic AI''-Assistent (ein KI-Agent)","Läuft direkt in deiner lokalen Arbeitsumgebung","Kann selbstständig Dateien lesen, erstellen & bearbeiten","Führt komplexe Workflows vollautomatisch aus","Arbeitet mit echten Tools, Skripten und Websuchen"]', 'Was genau ist Antigravity eigentlich? Ihr kennt wahrscheinlich alle ChatGPT oder Claude im Webbrowser. Das sind reine Chatbots: Man stellt eine Frage, bekommt eine Textantwort und muss das Ergebnis kopieren. Antigravity hingegen ist ein sogenannter ''KI-Agent''. Das bedeutet vereinfacht gesagt: Er hat Hände und Augen auf eurem Computer. Er arbeitet direkt in euren Projektordnern, kann eure lokalen Dateien lesen, neue Entwürfe speichern, im Web recherchieren und sogar Programme oder Skripte ausführen, um seine Aufgaben für euch zu erledigen. Er ist wie ein fleißiger digitaler Junior-Assistent.', 'mascot_think.png', './data/projects/1/temp_audio/slide_2.mp3', './data/projects/1/temp_video/slide_2.mp4'),
(3, 1, 3, 'Mehr als nur Anschreiben!', '["Hilft bei lästigen Routineaufgaben im Betriebssystem","Beantwortet Alltagsfragen zu deiner Hardware","Analysiert verständlich, warum dein PC langsam ist","Findet die Ursache, wenn Programme oder die Maus ruckeln","Prüft, ob Festplatte und Arbeitsspeicher in Ordnung sind"]', 'Die meisten Leute denken bei KI an Texte oder Übersetzungen. Aber Antigravity kann noch viel mehr in eurem Alltag tun. Kennt ihr das, wenn Photoshop oder Illustrator plötzlich laggen, der Mauszeiger zackig ruckelt oder die Festplatte fast voll ist? Typische Designer-Probleme, wenn man mit riesigen Texturen und Grafiken hantiert. Anstatt stundenlang in technischen Foren zu suchen, könnt ihr Antigravity einfach fragen: ''Warum ruckelt mein Rechner gerade?'' oder ''Habe ich noch genug Speicher?''. Er schaut direkt im System nach und liefert die Antwort.', 'slow_pc.png', './data/projects/1/temp_audio/slide_3.mp3', './data/projects/1/temp_video/slide_3.mp4'),
(4, 1, 4, 'Dein persönlicher PC-Doktor', '["Systemdiagnose ganz ohne technisches Kauderwelsch","Echtzeit-Check von CPU-Last, RAM und Speicherplatz","Identifiziert Programme, die deine Grafikkarte blockieren","Gibt dir konkrete, leicht verständliche Optimierungs-Tipps","Hilft aktiv beim Aufräumen (z. B. Temp-Dateien löschen)"]', 'Antigravity agiert hier wie euer persönlicher PC-Doktor. Er schaut quasi unter die Haube eures Rechners. Er analysiert die CPU, den RAM und die Belegung der Festplatten und übersetzt das in eine für uns Designer verständliche Sprache. Er sagt euch zum Beispiel: ''Hey, das Rendering-Programm im Hintergrund frisst 90% deines Speichers.'' Auf Wunsch kann er auch gleich beim Aufräumen helfen und temporären Datenmüll löschen, damit eure Kreativ-Software wieder flüssig läuft.', 'pc_doctor.png', './data/projects/1/temp_audio/slide_4.mp3', './data/projects/1/temp_video/slide_4.mp4'),
(5, 1, 5, 'Praxisbeispiel: Die Bewerbungs-Fabrik', '["Vorstellung des Projekts ''Bewerbungen2''","Problem: Manuelle Bewerbungen kosten enorm viel Zeit","Anschreiben müssen individuell auf jede Agentur passen","Lebensläufe müssen die Sprache des Zielunternehmens sprechen","Fehleranfälligkeit bei manuellem Copy-Paste"]', 'Um zu verdeutlichen, wie mächtig Antigravity ist, schauen wir uns ein konkretes Praxisbeispiel an: das Projekt ''Bewerbungen2''. Stellt euch vor, ihr wollt euch bei 10 verschiedenen Design-Agenturen bewerben. Jede Agentur hat einen anderen Fokus: Die eine macht Corporate Identity, die nächste UI/UX-Design, eine andere Packaging. Jedes Anschreiben und jeder Lebenslauf müsste manuell an das Portfolio der jeweiligen Agentur angepasst werden. Das dauert Tage und ist unglaublich eintönig. Antigravity verwandelt dieses Chaos in eine vollautomatische Pipeline.', 'paper_chaos.png', './data/projects/1/temp_audio/slide_5.mp3', './data/projects/1/temp_video/slide_5.mp4'),
(6, 1, 6, 'Schritt 1: Die KI lernt dich kennen', '["Basis-Daten: Lebenslauf & Zeugnisse im Ordner ''bewerbungsunterlagen''","Zusätzliche Quelle: Deine persönliche Website (z. B. www.tnickel-ki.de)","KI analysiert deine Design-Philosophie und Stärken","Identifiziert selbstständig passende Unternehmen im Web","Erstellt eine Vorschlagsliste und wartet auf dein Okay"]', 'Im ersten Schritt muss die KI natürlich erst mal verstehen, wer ihr seid. Im Ordner ''bewerbungsunterlagen'' liegen eure Standard-Dokumente wie eure Basis-Lebenslauf, Zertifikate und Zeugnisse. Zusätzlich geben wir der KI einen Weblink zu eurer Online-Präsenz – hier im Beispiel www.tnickel-ki.de. Antigravity liest die Website und eure Dokumente und baut ein tiefes Verständnis für eure Fähigkeiten, euren Design-Stil und eure Schwerpunkte auf. Anschließend sucht er im Web nach 4 bis 5 hochkarätigen Agenturen, die perfekt zu eurem Profil passen, und fragt euch um Erlaubnis, ob er für diese die Unterlagen vorbereiten soll.', 'research_you.png', './data/projects/1/temp_audio/slide_6.mp3', './data/projects/1/temp_video/slide_6.mp4'),
(7, 1, 7, 'Schritt 2: Der Master-Prompt (Der Dirigent)', '["Gesteuert über eine zentrale Textdatei: doc/masterprompt.txt","Definiert den exakten ''Fahrplan'' für die Pipeline","Zwingt die KI zur Live-Websuche vor der Dokumenterstellung","Sucht nach aktuellen News, Projekten und Tech-Stacks der Firmen","Nutzt diese Recherche als ''kreativen Aufhänger'' im Anschreiben"]', 'Der gesamte Ablauf wird durch den ''Master-Prompt'' gesteuert, der im Ordner ''doc'' liegt. Für uns Designer ist dieser Prompt wie ein Creative Director oder Dirigent. Es ist eine einfache Textdatei, die der KI sagt, wie sie vorgehen soll. Ein Kernbefehl darin ist der Deep-Research-Zwang: Bevor die KI ein Wort schreibt, muss sie das Zielunternehmen im Web suchen. Welche Kampagnen hat die Agentur in den letzten Monaten gelauncht? Welche Kunden betreuen sie? Diese echten Fakten baut Antigravity direkt als Aufhänger in eure Anschreiben ein, um echtes interesse zu signalisieren.', 'conductor.png', './data/projects/1/temp_audio/slide_7.mp3', './data/projects/1/temp_video/slide_7.mp4'),
(8, 1, 8, 'Schritt 3: Die Skripte (Die Werkzeuge)', '["Automatisierung durch Code im Ordner skripte","KI schreibt und nutzt kleine Helfer-Skripte (Python/PowerShell)","Konvertiert Markdown-Entwürfe automatisch in saubere PDFs","Kombiniert Anschreiben, Lebenslauf und Zeugnisse in Mappen","Räumt den Arbeitsbereich auf und löscht temporäre Dateien"]', 'Jetzt kommt das Handwerk. Um aus den generierten Texten fertige, versandbereite Mappen zu machen, nutzt Antigravity Skripte im Ordner ''skripte''. Für uns Designer ist das vergleichbar mit Photoshop-Aktionen oder Illustrator-Makros. Der Agent schreibt diese Skripte selbstständig oder führt sie aus. Sie wandeln die Textdokumente in PDF-Dateien um, bündeln das Anschreiben mit dem Lebenslauf und kopieren eure Zeugnisse dazu. Am Ende löscht die KI alle temporären Arbeitsdateien, damit kein Chaos auf eurer Festplatte entsteht.', 'toolbox.png', './data/projects/1/temp_audio/slide_8.mp3', './data/projects/1/temp_video/slide_8.mp4'),
(9, 1, 9, 'Schritt 4: Die fertigen Ergebnisse', '["Hauptordner Initiativbewerbungen_Aktuell wird erstellt","Saubere Unterordner für jedes einzelne Zielunternehmen","Individuell getextete, professionell formatierte Anschreiben & CVs","Alle Dokumente direkt als druck- und versandfertige PDFs","Walkthrough-Dokument verlinkt alle Ergebnisse direkt"]', 'Das Ergebnis ist einfach fantastisch. Nach nur wenigen Minuten findet ihr im Ordner ''Initiativbewerbungen_Aktuell'' für jedes Zielunternehmen einen perfekt sortierten Ordner. Darin liegen das fertige, personalisierte Anschreiben und der angepasste Lebenslauf als PDF, bereit zum Abschicken. Zusätzlich erstellt Antigravity eine kleine Übersichtsdatei, in der alle PDFs direkt verlinkt sind. Ihr könnt sie mit einem Klick öffnen, prüfen und abschicken. Die Arbeit von mehreren Tagen wurde in wenigen Minuten erledigt.', 'results_trophy.png', './data/projects/1/temp_audio/slide_9.mp3', './data/projects/1/temp_video/slide_9.mp4'),
(10, 1, 10, 'Kreativität entfesseln mit Antigravity', '["Die KI übernimmt die repetitive, zeitraubende Fleißarbeit","Der Mensch bleibt der Kurator, Designer und Entscheider","Mehr Zeit für das Wesentliche: Echte Designarbeit & Konzepte","Nahtlose Integration in deinen täglichen Workflow","Dein unsichtbarer, helfender Assistent im System"]', 'Zusammenfassend: Was bedeutet das für uns als Designer? Antigravity nimmt uns nicht die kreative Arbeit oder die gestalterische Vision weg. Es nimmt uns die administrative Fleißarbeit ab – das Suchen von Firmeninfos, das Anpassen von Texten, das Formatieren und Konvertieren von Dateien oder das Lösen von PC-Rucklern. Wir bleiben die Entscheider, die die finalen Ergebnisse freigeben. So haben wir den Kopf frei für das, was wir wirklich lieben: exzellentes Design und innovative Ideen. Vielen Dank für eure Aufmerksamkeit!', 'speed_boost.png', './data/projects/1/temp_audio/slide_10.mp3', './data/projects/1/temp_video/slide_10.mp4');

-- Seed slides for Example Project 2 (upsert by ID 11-15)
MERGE INTO slides (id, project_id, slide_number, title, bullets, notes, image_name, audio_file_path, video_file_path) KEY(id) VALUES 
(11, 2, 1, 'ElevenLabs API & Stimmenklon Guide', '["Eine Schritt-für-Schritt-Anleitung","für die Vertonung deines Vortrags."]', 'Herzlich willkommen! In diesem kurzen Leitfaden zeige ich dir Schritt für Schritt, wie du deinen ElevenLabs-Account einrichtest, deine eigene Stimme klonst und die notwendigen Schlüssel für unseren Vortragsgenerator erhältst. Keine Sorge – das Ganze dauert nur wenige Minuten und ist extrem unkompliziert. Lass uns direkt mit dem ersten Schritt starten!', 'mascot_hello.png', './data/projects/2/audio/slide_1.mp3', NULL),
(12, 2, 2, 'Schritt 1: Account erstellen', '["Besuche die Webseite elevenlabs.io", "Erstelle einen kostenlosen Account", "Anmeldung via E-Mail, Google oder GitHub", "Automatisch freies monatliches Zeichenkontingent"]', 'Als Erstes gehen wir auf die Website elevenlabs.io. Dort kannst du dich ganz einfach registrieren – entweder klassisch mit deiner E-Mail-Adresse oder direkt über deinen bestehenden Google- oder GitHub-Account. Nach der Anmeldung hast du sofort Zugriff auf das Dashboard und ein monatliches Freikontingent an Zeichen für die Sprachsynthese.', 'mascot_think.png', './data/projects/2/audio/slide_2.mp3', NULL),
(13, 2, 3, 'Schritt 2: API-Schlüssel kopieren', '["Klicke unten links auf dein Profil-Symbol", "Wähle den Menüpunkt ''Profile + API-Keys''", "Klicke auf das Auge-Symbol zum Einblenden", "Kopiere den API-Schlüssel in unseren Generator"]', 'Um unseren Vortragsgenerator mit ElevenLabs zu verbinden, benötigen wir einen API-Schlüssel. Klicke dazu unten links in deinem ElevenLabs-Dashboard auf dein Profilbild oder deinen Benutzernamen und wähle den Menüpunkt ''Profile + API-Keys''. Dort siehst du deinen API-Schlüssel. Klicke auf das kleine Auge-Symbol, um ihn anzuzeigen, und kopiere ihn in die Einstellungen unseres Generators.', 'toolbox.png', './data/projects/2/audio/slide_3.mp3', NULL),
(14, 2, 4, 'Schritt 3: Eigene Stimme klonen', '["Gehe links im Menü auf ''Voices''", "Klicke auf ''Add voice'' und wähle ''Instant Voice Cloning''", "Lade eine 1-2 minütige Sprachaufnahme von dir hoch", "Achte auf eine ruhige Umgebung ohne Hintergrundgeräusche"]', 'Jetzt klonen wir deine Stimme! Klicke im Menü links auf ''Voices'' und dann auf ''Add voice''. Wähle dort ''Instant Voice Cloning''. Lade nun eine kurze Audioaufnahme von dir hoch. Am besten nimmst du dich mit dem Handy oder Mikrofon für etwa 1 bis 2 Minuten in einer absolut ruhigen Umgebung auf, während du einen deutschen Text vorliest. Je sauberer die Aufnahme ist, desto originalgetreuer klingt am Ende deine KI-Stimme.', 'pc_doctor.png', './data/projects/2/audio/slide_4.mp3', NULL),
(15, 2, 5, 'Schritt 4: Voice-ID kopieren', '["Deine Klonstimme erscheint in der Voices-Bibliothek", "Klicke auf das kleine ID-Symbol unter dem Namen", "Kopiere die eindeutige Voice-ID Zeichenkette", "Füge sie in die Einstellungen des Generators ein"]', 'Sobald die Stimme erstellt ist, erscheint sie in deiner Stimmen-Bibliothek. Direkt unter dem Namen deiner Klonstimme siehst du ein kleines ID-Symbol (oder einen Textlink ''ID anzeigen''). Klicke darauf und kopiere die eindeutige ID-Zeichenfolge. Diese ID fügst du in den Einstellungen unseres Vortragsgenerators ein. Nun ist das System bereit und du kannst deine Vorträge vollautomatisch mit deiner eigenen Stimme vertonen lassen!', 'results_trophy.png', './data/projects/2/audio/slide_5.mp3', NULL);

-- Restart auto-increment sequences dynamically based on the max ID in the tables to prevent primary key collisions on server restarts
ALTER TABLE projects ALTER COLUMN id RESTART WITH (SELECT COALESCE(MAX(id), 0) + 1 FROM projects);
ALTER TABLE slides ALTER COLUMN id RESTART WITH (SELECT COALESCE(MAX(id), 0) + 1 FROM slides);
ALTER TABLE prompt_history ALTER COLUMN id RESTART WITH (SELECT COALESCE(MAX(id), 0) + 1 FROM prompt_history);
ALTER TABLE image_sets ALTER COLUMN id RESTART WITH (SELECT COALESCE(MAX(id), 0) + 1 FROM image_sets);
ALTER TABLE image_set_entries ALTER COLUMN id RESTART WITH (SELECT COALESCE(MAX(id), 0) + 1 FROM image_set_entries);

